//
//  KMeans.swift
//  FreedomSound
//
//  Created by Gaëtan Boyals on 22/06/2026.
//

// This file has been fully generated by Claude. Need to deep dive into it

import UIKit
import Accelerate

struct KMeansColorExtractor {
    
    // MARK: - Types
    struct RGBPoint {
        var r, g, b: Float
    }
    
    // MARK: - Public API
    static func extract(from image: UIImage, colorCount k: Int = 3, iterations: Int = 10) -> [UIColor] {
        guard let pixels = samplePixels(from: image) else { return [.gray] }
        
        var centroids = initCentroids(from: pixels, k: k)
        var assignments = [Int](repeating: 0, count: pixels.count)
        
        for _ in 0..<iterations {
            // Étape 1 : assigner chaque pixel au centroïde le plus proche
            var changed = false
            for i in 0..<pixels.count {
                let nearest = nearestCentroid(for: pixels[i], centroids: centroids)
                if assignments[i] != nearest { changed = true }
                assignments[i] = nearest
            }
            guard changed else { break }  // convergence atteinte
            
            // Étape 2 : recalculer les centroïdes
            centroids = recomputeCentroids(pixels: pixels, assignments: assignments, k: k)
        }
        
        return centroids.map { UIColor(red: CGFloat($0.r), green: CGFloat($0.g), blue: CGFloat($0.b), alpha: 1) }
    }
    
    // MARK: - Internals
    private static func samplePixels(from image: UIImage, size: Int = 64) -> [RGBPoint]? {
        let targetSize = CGSize(width: size, height: size)
            
            // Force RGBA explicitement — plus de surprise sur l'ordre des canaux
            let colorSpace = CGColorSpaceCreateDeviceRGB()
            let bitmapInfo = CGBitmapInfo(rawValue: CGImageAlphaInfo.premultipliedLast.rawValue) // RGBA
            
            guard let context = CGContext(
                data: nil,
                width: size,
                height: size,
                bitsPerComponent: 8,
                bytesPerRow: size * 4,
                space: colorSpace,
                bitmapInfo: bitmapInfo.rawValue
            ) else { return nil }
            
            context.draw(image.cgImage!, in: CGRect(x: 0, y: 0, width: size, height: size))
            
            guard let data = context.data else { return nil }
            let bytes = data.bindMemory(to: UInt8.self, capacity: size * size * 4)
            
            var pixels: [RGBPoint] = []
            for i in 0..<(size * size) {
                let offset = i * 4
                let r = Float(bytes[offset])     / 255  // R garanti
                let g = Float(bytes[offset + 1]) / 255  // G garanti
                let b = Float(bytes[offset + 2]) / 255  // B garanti
                // offset + 3 = Alpha, ignoré
                
                let brightness = (r + g + b) / 3
                guard brightness > 0.08 && brightness < 0.92 else { continue }
                pixels.append(RGBPoint(r: r, g: g, b: b))
            }
            return pixels
    }
    
    private static func initCentroids(from pixels: [RGBPoint], k: Int) -> [RGBPoint] {
        // K-means++ : chaque nouveau centroïde est choisi
        // avec une probabilité proportionnelle à sa distance au plus proche centroïde existant
        var centroids: [RGBPoint] = [pixels.randomElement()!]
        
        while centroids.count < k {
            let distances = pixels.map { p -> Float in
                let d = nearestDistance(for: p, centroids: centroids)
                return d * d
            }
            let total = distances.reduce(0, +)
            var pick = Float.random(in: 0..<total)
            for (i, d) in distances.enumerated() {
                pick -= d
                if pick <= 0 { centroids.append(pixels[i]); break }
            }
        }
        return centroids
    }
    
    private static func nearestCentroid(for point: RGBPoint, centroids: [RGBPoint]) -> Int {
        var best = 0
        var bestDist = Float.greatestFiniteMagnitude
        for (i, c) in centroids.enumerated() {
            let d = distance(point, c)
            if d < bestDist { bestDist = d; best = i }
        }
        return best
    }
    
    private static func nearestDistance(for point: RGBPoint, centroids: [RGBPoint]) -> Float {
        centroids.map { distance(point, $0) }.min() ?? 0
    }
    
    private static func distance(_ a: RGBPoint, _ b: RGBPoint) -> Float {
        let dr = a.r - b.r, dg = a.g - b.g, db = a.b - b.b
        return dr*dr + dg*dg + db*db  // distance euclidienne au carré (évite sqrt inutile)
    }
    
    private static func recomputeCentroids(pixels: [RGBPoint], assignments: [Int], k: Int) -> [RGBPoint] {
        var sums = [(r: Float, g: Float, b: Float, count: Int)](repeating: (0,0,0,0), count: k)
        for (i, p) in pixels.enumerated() {
            let c = assignments[i]
            sums[c].r += p.r; sums[c].g += p.g; sums[c].b += p.b; sums[c].count += 1
        }
        return sums.map { s in
            guard s.count > 0 else { return pixels.randomElement()! }
            return RGBPoint(r: s.r / Float(s.count), g: s.g / Float(s.count), b: s.b / Float(s.count))
        }
    }
}
