//
//  KMeansBackground.swift
//  FreedomSound
//
//  Created by Gaëtan Boyals on 22/06/2026.
//

// This file has been fully generated by Claude. Need to dive in this

import SwiftUI

extension [UIColor] {
    /// Trie les couleurs par luminosité pour un gradient cohérent
    func sortedByLuminance() -> [UIColor] {
        sorted {
            var l1: CGFloat = 0, l2: CGFloat = 0
            $0.getHue(nil, saturation: nil, brightness: &l1, alpha: nil)
            $1.getHue(nil, saturation: nil, brightness: &l2, alpha: nil)
            return l1 > l2
        }
    }
}

struct KMeansGradientBackground: View {
    let artwork: UIImage?
    let colorCount: Int = 3

    @State private var gradientColors: [Color] = [.black]

    var body: some View {
        LinearGradient(
            colors: gradientColors,
            startPoint: .topLeading,
            endPoint: .bottomTrailing
        )
        .ignoresSafeArea()
        .animation(.easeInOut(duration: 0.5), value: gradientColors.count)
        .task(id: artwork) {
            await updateGradient()
        }
    }

    private func updateGradient() async {
        guard let image = artwork else { return }

        let colors = await Task.detached(priority: .userInitiated) {
            KMeansColorExtractor
                .extract(from: image, colorCount: colorCount, iterations: 12)
                .sortedByLuminance()
        }.value

        withAnimation(.easeInOut(duration: 0.5)) {
            // Ajouter une version assombrie en bas pour la lisibilité du texte
            gradientColors = colors.map { Color($0) } + [Color(.systemBackground).opacity(0.15)]
        }
    }
}
